import { StyleSheet } from "react-native";

const StyleTelaConfiguracao = StyleSheet.create({
  main: {
    flex: 1,
    textAlign: "center",
    backgroundColor: "#113036",
  },
  container: {
    backgroundColor: "#113036",
    flex: 1,
    alignItems: "center",
  },
  card: {
    width: 370,
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#051C21",
    borderColor: "#fff",
    borderWidth: 1,
    marginBottom: 30,
  },
  titulo: {
    marginTop: 30,
    marginBottom: 40,
    fontSize: 32,
    fontWeight: 700,
    color: "#fff",
    alignItems: "center",
    textAlign: "center",
  },
  sobTitulo: {
    textAlign: "center",
    marginBottom: 1,
    fontSize: 24,
    fontWeight: 700,
    color: "#fff",
  },
  sobTitulo1: {
    textAlign: "center",
    marginBottom: 1,
    fontSize: 22,
    fontWeight: 700,
    color: "#fff",
  },
  sobTitulo2: {
    marginBottom: 1,
    fontSize: 24,
    fontWeight: 700,
    color: "#fff",
  },
  textoPadrao: {
    marginTop: 16,
    color: "#cccccc",
    fontWeight: 500,
    fontSize: 18,
    width: 330,
    alignItems: "center",
    textAlign: "justify",
  },
  campoinputNomes: {
    flexDirection: "row",
  },
  inputTexto: {
    height: 45,
    width: 340,
    padding: 0,
    margin: 1,
    color: "#fff",
    backgroundColor: "#416169",
    borderRadius: 6,
    marginBottom: 6,
  },

  inputTextoNome: {
    height: 45,
    width: 168,
    padding: 0,
    marginRight: 2,
    margin: 1,
    color: "#fff",
    backgroundColor: "#416169",
    borderRadius: 6,
    marginBottom: 6,
  },
  inputTextoSobrenome: {
    height: 45,
    width: 168,
    padding: 0,
    marginLeft: 2,
    margin: 1,
    color: "#fff",
    backgroundColor: "#416169",
    borderRadius: 6,
    marginBottom: 6,
  },
  imgLogo: {
    marginTop: 45,
    width: 165,
    height: 100,
  },
  button: {
    width: 340,
    height: 45,
    color: "#000",
    backgroundColor: "#B3DCE5",
    borderRadius: 6,
    marginBottom: 0,
    marginTop: 15,
    paddingTop: 5,
    marginBottom: 10,
  },
  buttonDelete: {
    width: 350,
    height: 45,
    color: "#fff",
    backgroundColor: "#B3DCE5",
    borderRadius: 6,
    marginBottom: 0,
    marginTop: 5,
    paddingTop: 5,
  },
  textoButton: {
    color: "#000",
    fontSize: 18,
    fontWeight: 700,
  },
  textoButtonDelete: {
    color: "#000",
    fontSize: 18,
    fontWeight: 700,
  },
  checkboxContainer: {
    borderColor: "#fff",
    borderStyle: "dotted",
    borderWidth: 0.9,
    flexDirection: "row",
    marginBottom: 6,
  },
  checkbox: {
    alignSelf: "center",
  },
  label: {
    width: 299,
    color: "#eee",
    fontWeight: 500,
    margin: 4,
  },
  anexo: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5FCFF",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
  },
  image: {
    width: "80%",
    height: 30,
    marginTop: 20,
  },
  developer: {
    marginTop: 70,
    marginBottom: 15,
    color: "#93B8C2",
  },
});

export default StyleTelaConfiguracao;
