import { StyleSheet } from 'react-native';

const StyleTelaConfiguracao = StyleSheet.create({

    main: {
        flex: 1,
        textAlign: 'center',
        backgroundColor: '#113036',
    },
    container: {
        backgroundColor: '#113036',
        flex: 1,
        // justifyContent: 'center',
        // textAlign: 'center',
        // justifyItems: 'center',
        alignItems: 'center',
        // marginLeft:2-,
    },
    titulo: {
        marginTop: 30,
        marginBottom: 40,
        fontSize: 32,
        fontWeight: 700,
        color: '#fff',
        alignItems: 'center',
        textAlign: 'center',
    },
    sobTitulo: {
        // marginTop: 30,
        marginLeft:-200,
        marginBottom: 1,
        fontSize: 24,
        fontWeight: 700,
        color: '#fff',
    },
    sobTitulo1: {
        // marginTop: 20,
        marginLeft:-170,
        marginBottom: 1,
        fontSize: 24,
        fontWeight: 700,
        color: '#fff',
    },
    sobTitulo2: {
        // marginTop: 30,
        marginLeft:-62,
        marginBottom: 1,
        fontSize: 24,
        fontWeight: 700,
        color: '#fff',
    },
    textoPadrao: {
        marginTop: 16,
        color: "#cccccc",
        fontWeight: 500,
        fontSize: 18,
        width: 330,
        alignItems: 'center',
        textAlign: 'justify',
    },
    campoinputNomes: {
        flexDirection: 'row',
    },
    inputTexto: {
        height: 45,
        width: 350,
        padding: 0,
        margin: 1,
        color: '#fff',
        backgroundColor: '#416169',
        borderRadius: 6,
    },
    inputTextoDescricao: {
        height: 120,
        width: 350,
        paddingLeft: 10,
        paddingTop: -100,
        margin: 5,
        color: '#fff',
        backgroundColor: 'rgba(204, 204, 204, 0.3)',
        borderRadius: 10,
    },
    inputTextoNome: {
        height: 45,
        width: 170,
        padding: 0,
        marginRight: 3,
        margin: 1,
        color: '#fff',
        backgroundColor: '#416169',
        borderRadius: 6,
    },
    inputTextoSobrenome: {
        height: 45,
        width: 170,
        padding: 0,
        marginLeft: 3,
        margin: 1,
        color: '#fff',
        backgroundColor: '#416169',
        borderRadius: 6,
    },
    imgLogo: {
        marginTop: 45,
        width: 165,
        height: 100,
    },
    button: {
        width: 350,
        height: 45,
        color: '#000',
        backgroundColor: '#B3DCE5',
        borderRadius: 6,
        marginBottom: 0,
        marginTop: 5,
        paddingTop: 5,
        marginBottom: 60,
    },
    buttonDelete: {
        width: 350,
        height: 45,
        color: '#fff',
        backgroundColor: '#B3DCE5',
        borderRadius: 6,
        marginBottom: 0,
        marginTop: 5,
        paddingTop: 5,

    },
    textoButton: {
        color: '#000',
        fontSize: 18,
        fontWeight: 700,
    },
    textoButtonDelete: {
        color: '#000',
        fontSize: 18,
        fontWeight: 700,
    },
    checkboxContainer: {
        marginLeft:-50,
        width: 315,
        flexDirection: 'row',
        marginBottom: 0,
    },
    checkbox: {
        alignSelf: 'center',
    },
    label: {
        color: '#eee',
        fontWeight: 500,
        margin: 4,
    },
    anexo: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F5FCFF',
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 20,
    },
    image: {
        width: '80%',
        height: 30,
        marginTop: 20,
    },
    developer: {
        marginTop:60,
        marginBottom: 20,
        color: '#93B8C2',
    },
})

export default StyleTelaConfiguracao;